### ISSUE TITLE
add test for servo changes that will be rejected by `mach vendor rust`

### ISSUE THREAD

**Issue by globau** [servo/homu#130]
i don't know if this is possible or palatable, but i see value in adding servo tests for changes that will be rejected by mozilla-central's `mach vendor rust`.

`mach vendor rust` performs some checks (listed below) and will throw an error should any of them fail to pass.  should this happen it would leave `servo --> gecko` synching in a state that would require manual work to resolve (likely involving backing out the servo change).  catching these before they are merged to servo would save time and effort.

current checks:
- whitelist of acceptable licenses
https://hg.mozilla.org/mozilla-central/file/tip/python/mozbuild/mozbuild/vendor_rust.py#l129
- maximum file size
https://hg.mozilla.org/mozilla-central/file/tip/python/mozbuild/mozbuild/vendor_rust.py#l295

**Comment by Manishearth** [comment]
one slight issue is that the m-c lockfile isn't actually in the servo tree, so if a version bump on that side brings things in it could be weird.

Though I guess the only way a version bump would be triggered is explicit lockfile editing so that's going to be rare.

Best way to implement this would be a mach step in the servo repo, and an additional check in buildbot_steps.yml (doesn't need any homu changes)

**Comment by jdm** [comment]
Not relevant for Firefox or homu any more.
